table 'marts dim_payment_type'
	lineageTag: 3baf6b27-bcca-424f-a01e-ea0d5e484a0c

	column payment_type_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7ba9b87c-c64b-48f2-906f-50ec3bf78ad5
		summarizeBy: none
		sourceColumn: payment_type_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: int64
		formatString: 0
		lineageTag: c0edd9b0-f916-410e-80d3-496c1a776a00
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_type_name
		dataType: string
		lineageTag: 57e61b24-42b6-4d16-847f-c781ec8a1a60
		summarizeBy: none
		sourceColumn: payment_type_name

		annotation SummarizationSetBy = Automatic

	column is_unrecognized_payment_type
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e2da6f57-cf50-4907-9153-cb475bb96f89
		summarizeBy: none
		sourceColumn: is_unrecognized_payment_type

		annotation SummarizationSetBy = Automatic

	column is_documented_unknown_payment_type
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 43d75a48-24ec-4582-92a0-dc0dcd43afdb
		summarizeBy: none
		sourceColumn: is_documented_unknown_payment_type

		annotation SummarizationSetBy = Automatic

	partition 'marts dim_payment_type' = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("localhost:5433", "mobility_db", [CreateNavigationProperties = false]),
				  #"Navigation 1" = Source{[Schema = "marts", Item = "dim_payment_type"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1",{{"payment_type_key", Int64.Type}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

