table 'marts dim_date'
	lineageTag: c7fc9325-e448-4cb5-aa3f-9857881df12a
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 598f9471-f6a8-4e48-ae67-db2afbaa4dc0
		summarizeBy: none
		sourceColumn: date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 66f8b8c2-5dfd-4b1c-a68b-791250439802
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column calendar_year
		dataType: int64
		formatString: 0
		lineageTag: 91fb4e62-aa0d-490f-bd87-e9adb5604188
		summarizeBy: sum
		sourceColumn: calendar_year

		annotation SummarizationSetBy = Automatic

	column calendar_quarter
		dataType: int64
		formatString: 0
		lineageTag: 932e3afc-ace7-4a3a-941e-c73cc00d5c72
		summarizeBy: sum
		sourceColumn: calendar_quarter

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: b7f9b65e-ad10-4fde-850c-9563c79a7118
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 943a494a-ede1-4933-9cfc-5602420c5a41
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: f2da9500-1fbd-4e15-b141-438a97c5725b
		summarizeBy: sum
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 3f2088dc-eced-419e-91e6-89b535c3ed7f
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: b71bd1b2-5fa2-437d-8e71-1d0ea38e42c9
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column iso_week
		dataType: int64
		formatString: 0
		lineageTag: 48d4ee16-12f2-43b8-9d50-60dfa53a8dfe
		summarizeBy: sum
		sourceColumn: iso_week

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c4adc36c-515d-4976-bfac-33e4a915b349
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	partition 'marts dim_date' = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("localhost:5433", "mobility_db", [CreateNavigationProperties = false]),
				  #"Navigation 1" = Source{[Schema = "marts", Item = "dim_date"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1",{{"calendar_year", Int64.Type}, {"calendar_quarter", Int64.Type}, {"month_number", Int64.Type}, {"day_of_month", Int64.Type}, {"day_of_week", Int64.Type}, {"iso_week", Int64.Type}, {"is_weekend", type logical}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

